package com.bungeee.android.swapi.data.database;

import android.arch.persistence.room.Entity;
import android.arch.persistence.room.Ignore;
import android.arch.persistence.room.Index;
import android.arch.persistence.room.PrimaryKey;
import android.arch.persistence.room.Room;
import android.arch.persistence.room.TypeConverters;

import java.sql.Array;
import java.util.ArrayList;
import java.util.List;

/**
 * Defines the schema of a table in {@link Room} for a single weather
 * forecast. The date is used as an {@link Index} so that its uniqueness can be ensured. Indexes
 * also allow for fast lookup for the column.
 */
@Entity(tableName = "film", indices = {@Index(value = {"episode_id"}, unique = true)})
public class FilmEntry {

    /**
     * Makes sure the id is the primary key (ensures uniqueness), is auto generated by {@link Room}.
     */
    @PrimaryKey(autoGenerate = true)
    private int id;
    private String title;
    private String episode_id;
    private String opening_crawl;
    private String director;
    private String producer;
    private String release_date;
	private ArrayList characters;

    /**
     * This constructor is used by OpenWeatherJsonParser. When the network fetch has JSON data, it
     * converts this data to FilmEntry objects using this constructor.
     *
     * @param title 			Title of the film
     * @param episode_id        Episode of the film
     * @param opening_crawl     Opening text of the episode
     * @param director          Director of the film
     * @param producer      	Producers of the film
     * @param characters      	Urls of the characters in the film
     * @param release_date      Release data of the film
     */
    @Ignore
    public FilmEntry(String title, String episode_id, String opening_crawl, String director, String producer,String release_date, ArrayList characters ) {
        this.title = title;
        this.episode_id = episode_id;
        this.opening_crawl = opening_crawl;
        this.director = director;
        this.producer = producer;
		this.characters = characters;
        this.release_date = release_date;
    }

    // Constructor used by Room to create FlimEntries
    public FilmEntry(int id, String title, String episode_id, String opening_crawl, String director, String producer,String release_date, ArrayList characters) {

        this.id = id;
        this.title = title;
        this.episode_id = episode_id;
        this.opening_crawl = opening_crawl;
        this.director = director;
        this.producer = producer;
		this.characters = characters;
        this.release_date = release_date;

    }

    public int getId() {
        return id;
    }

    public String getTitle() {
        return title;
    }

    public String getEpisode_id() {
        return episode_id;
    }

    public String getOpening_crawl() {
        return opening_crawl;
    }

    public String getDirector() {
        return director;
    }

    public String getProducer() {
        return producer;
    }

	public String getRelease_date() {
		return release_date;
	}

	public ArrayList<String> getCharacters() {
		return characters;
	}

}